#spring.application.name=back-end
#openai.model=gpt-3.5-turbo
#openai.api.url=https://api.openai.com/v1/chat/completions
#openai.api.key=${OPEN_AI_API_KEY}

spring:
  application:
    name: potion-imperium-back-end

openai:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ${OPEN_AI_API_KEY}